refator(mm-search): fetch 20 article onces
mirror-media/Adam pull request #1042
Opened 2024-07-31 14:10 UTC by v61265

### 參考資料
- [asana](https://app.asana.com/0/1207894274504432/1207863564479424/f)

2024-08-01 03:38 UTC, caesarWHLee requested changes
目前頁面是變成一頁顯示 20 則，跟 12 則的需求不符，建議釐清一頁的顯示數量和每次抓取的數量，兩者是可以分開的，但需要確認有正確設定

可以考慮把 Infinite-Scroll 改成 [react-infinite-scroll-list](https://www.npmjs.com/package/@readr-media/react-infinite-scroll-list)

2024-08-02 05:55 UTC, v61265 commented
感謝詳細說明，已於 [bd81f04](https://github.com/mirror-media/Adam/pull/1042/commits/bd81f047246068c2902ed6b9f50a3958c6c9b8b6) 改為使用 `@readr-media/react-infinite-scroll-list` 並區分 fetch 數量和 render 數量。

2024-08-06 06:41 UTC, caesarWHLee requested changes
http://localhost:3000/search/v3/%E9%83%AD%E5%8F%B0%E9%8A%98

滑到最後會遇到錯誤

![圖片](https://github.com/user-attachments/assets/cc9bd1ce-d1b4-4035-9454-f0d8caf43ae7)

2024-08-06 06:41 UTC, caesarWHLee commented on packages/mirror-media-search/components/searched-articles.js
> +// import InfiniteScrollList from './infinite-scroll-list'
remvoe unused code

2024-08-19 07:22 UTC, v61265 commented on packages/mirror-media-search/components/searched-articles.js
> +// import InfiniteScrollList from './infinite-scroll-list'
以上問題皆於 [4597840](https://github.com/mirror-media/Adam/pull/1042/commits/45978403851df3c717a74e23887087f18b5554f1) 修改完成。
另外因為有 redis cache 的原因，有些關鍵字已經被 cache 找不到關鍵字，如果要驗收到一百篇的話推薦使用關鍵字「太魯閣」。

2024-08-19 14:36 UTC, caesarWHLee requested changes
目前塞進 `InfiniteScrollList` 的 `pageSize` 是設定 12 但是 `fetchPostsFromPage` 中卻是以一頁 20 筆的資料去拿，導致 pagination 的控制會有問題，所以會遇到 page = 8 這種 request 但實際上 start 是 invalid 的值 : (8 - 1) * 20 + 1 = 141，目前直接看遇到的問題是實際搜尋數量超過 100 筆資料的關鍵字在頁面上只會顯示到 90 筆

建議把 fetchPostsFromPage 的數量和 pageSize 調成一樣，然後 `programmable-search` utils 中去 handle take = 12，比如說拿 0 - 11 筆資料時就會需要打兩次 google api 來拿到 0-9 和 10 - 19  的資料，再組出 0 - 11 的資料回傳回來，需要注意的是第 97 - 99 筆的資料需要修改一下 take 的值不然 google api 會報錯。

2024-08-19 14:36 UTC, caesarWHLee commented on packages/mirror-media-search/components/searched-articles.js
> +    if ((page - 1) * 20 + 1 > 100) return []
在 `pageSize` 和 `amountOfElements` 正確設定的狀況下，page 的設定不會超過 8 頁 (100/12)，可以不用這個限制

2024-08-20 05:08 UTC, v61265 commented
不好意思想請教一下，目前的寫法確實可以做到只拿 12 筆資料，但一樣是要發兩次 api，只拿 12 筆會不會有點消耗效能（比起一次拿 20 筆）。針對這個問題目前想到的是修改 totalAmount 的值，騙他我們只有 100 * (12/20) = 60 筆資料，他打五次但我們可以拿到 100 筆資料，但就是有點違背該 props 原本意圖，可讀性下降？

2024-08-20 05:13 UTC, caesarWHLee commented
> 不好意思想請教一下，目前的寫法確實可以做到只拿 12 筆資料，但一樣是要發兩次 api，只拿 12 筆會不會有點消耗效能（比起一次拿 20 筆）。針對這個問題目前想到的是修改 totalAmount 的值，騙他我們只有 100 * (12/20) = 60 筆資料，他打五次但我們可以拿到 100 筆資料，但就是有點違背該 props 原本意圖，可讀性下降？

不應該是想辦法欺騙 `InfiniteScrollList` 來達成少打 API 的效果，這樣只會產生不可預期的 bug (像是現在遇到的只顯示 90 筆資料)，不管是拿 12 筆或是 20 筆一樣都是打兩次 google api，回傳的結果會被存在 redis 中，所以不會有太大的差別

2024-08-20 10:45 UTC, v61265 commented
感謝說明，已於 [0e31204](https://github.com/mirror-media/Adam/pull/1042/commits/0e312044ede74219e77e037b6211c5a4a8b6eda1) 修改

2024-08-20 14:59 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +    const takeAmount = parseInt(params.takeAmount || query.takeAmount || 10)
不應該直接用 query 的內容，僅可用被 searchQuerySchema.validate 後的 params 的內容

2024-08-20 14:59 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +        num: 10, // 每次最多取 10 個
應用 `PROGRAMABLE_SEARCH_NUM` 表示

2024-08-20 14:59 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +      const redisKey = `${prefix}_${exactTerms}_${adjustedStart}_10}`
10 鷹用 `PROGRAMABLE_SEARCH_NUM` 表示

2024-08-20 14:59 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +        if (JSON.parse(searchResultCache).items) {
讓這個執行一次就好了
```JavaScript
JSON.parse(searchResultCache).items
```

2024-08-20 14:59 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +          continue
Ln. 97 ~ 109 應該放到 `try { }` 裡面，消除不必要的 continue

2024-08-20 14:59 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +    const exactTerms = params.exactTerms || query.exactTerms || 10
exactTerms 的 fallback 是 number ?

2024-08-20 14:59 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +    let adjustedStart = Math.floor(startIndex / 10) * 10 + 1
10 鷹用 `PROGRAMABLE_SEARCH_NUM` 表示

2024-08-20 14:59 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +          resData.queries.nextPage === undefined
Ln. 106 與 Ln. 82 和 Ln. 90 搭配一起看，
`resData.queries.nextPage` 鷹調整為 `resData?.queries?.nextPage`，
另外，`allItems.length >= takeAmount` 是多餘的

2024-08-20 14:59 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +          console.log(
有錯誤重試次數上限嗎？

2024-08-20 14:59 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +    const sliceStartIndex = Math.max(0, startIndex - originAdjustedStart)
這會有負數的情況？

2024-08-20 14:59 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
思考一些情境，
start 為 6，takeAmout 為 6，照理來說要抓 2 次有辦法拿出 6 ...12 的內容，但按照目前的程式邏輯，應該只會拿到 6 to 10
start 為 6，takeAmount 為 18，照理來說要抓 3 次有辦法拿出 6 ... 24 的內容，但按照目前的程式邏輯，應該只會拿到 6 ... 20

2024-08-20 14:59 UTC, erase2004 commented on packages/mirror-media-search/components/searched-articles.js
> +          takeAmount: Math.min(12, totalResults - (page - 1) * 12),
12 應該同這裡用設定管理
[/pages/search/v3/[searchTerms].js](https://github.com/mirror-media/Adam/pull/1042/files#diff-198e46730b31e1300b3b74ca5628bb102ca69d9cb45afa591aad29c5a0c5e6fe)

2024-08-20 14:59 UTC, erase2004 commented on packages/mirror-media-search/components/searched-articles.js
> +        return <ArticleList renderList={renderList} searchTerms={searchTerms} />
這個改動比較沒必要

2024-08-21 05:31 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
start=6 takeAmount=6 adjustedStartIndex=1
會拿到 1~10（這部分多半已經有 redisCache 可拿）以及 11~20，然後用 slice 取得 6 ~ 12 筆資料。

start=6 takeAmount=18 adjustStartIndex=1
會拿到 1~10、11~20 還有 21~30，最後拼湊出 6~26 回傳。

2024-08-21 05:45 UTC, v61265 commented on packages/mirror-media-search/components/searched-articles.js
> +        return <ArticleList renderList={renderList} searchTerms={searchTerms} />
這是 debug 痕跡被發現了 XD 感謝提醒，已於 [41b8352](https://github.com/mirror-media/Adam/pull/1042/commits/41b83524a7997ce16170cbd2518c9571215e33c7) 修改回來。

2024-08-21 05:45 UTC, v61265 commented on packages/mirror-media-search/components/searched-articles.js
> +          takeAmount: Math.min(12, totalResults - (page - 1) * 12),
感謝提醒，已於 [41b8352](https://github.com/mirror-media/Adam/pull/1042/commits/41b83524a7997ce16170cbd2518c9571215e33c7) 修改，將 12 統一交由 const 管理。

2024-08-21 05:45 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +    const sliceStartIndex = Math.max(0, startIndex - originAdjustedStart)
好像沒有 XD 感謝提醒，已於 [41b8352](https://github.com/mirror-media/Adam/pull/1042/commits/41b83524a7997ce16170cbd2518c9571215e33c7) 修改～

2024-08-21 05:46 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +          console.log(
目前應該是沒有就跳過了，還是目前寫法是會重複打到有？

2024-08-21 05:46 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +    let adjustedStart = Math.floor(startIndex / 10) * 10 + 1
感謝提醒，已於 [41b8352](https://github.com/mirror-media/Adam/pull/1042/commits/41b83524a7997ce16170cbd2518c9571215e33c7) 修改

2024-08-21 05:47 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +    const exactTerms = params.exactTerms || query.exactTerms || 10
對齁，先改成空字串，已於 [41b8352](https://github.com/mirror-media/Adam/pull/1042/commits/41b83524a7997ce16170cbd2518c9571215e33c7) 修改

2024-08-21 05:47 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +          continue
感謝提醒，已於 [41b8352](https://github.com/mirror-media/Adam/pull/1042/commits/41b83524a7997ce16170cbd2518c9571215e33c7) 修改

2024-08-21 05:47 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +        if (JSON.parse(searchResultCache).items) {
感謝提醒，已於 [41b8352](https://github.com/mirror-media/Adam/pull/1042/commits/41b83524a7997ce16170cbd2518c9571215e33c7) 修改

2024-08-21 05:48 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +      const redisKey = `${prefix}_${exactTerms}_${adjustedStart}_10}`
感謝提醒，已於 [41b8352](https://github.com/mirror-media/Adam/pull/1042/commits/41b83524a7997ce16170cbd2518c9571215e33c7) 修改
另外這個 review 時間看起來有點不妙，要記得睡覺捏 ><

2024-08-21 05:48 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +        num: 10, // 每次最多取 10 個
感謝耐心一個一個標出來，已於 [41b8352](https://github.com/mirror-media/Adam/pull/1042/commits/41b83524a7997ce16170cbd2518c9571215e33c7) 修改

2024-08-21 05:48 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +    const takeAmount = parseInt(params.takeAmount || query.takeAmount || 10)
感謝提醒，已於 [41b8352](https://github.com/mirror-media/Adam/pull/1042/commits/41b83524a7997ce16170cbd2518c9571215e33c7) 修改

2024-08-21 05:53 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +          resData.queries.nextPage === undefined
對齁，先於 [5b58899](https://github.com/mirror-media/Adam/pull/1042/commits/5b588998819eb8a33fd22bf9618974f6b8401c7a) 修改加上 ? 防止錯誤。
另外想請教 `allItems.length >= takeAmount` 為什麼是多餘的呢？假如我今天就只要抓 1~20 筆，nextPage 一定會有東西，但我其實已經拿完了，因此才需要比較拿到的值（20）和 takeAmount（12）

2024-08-21 06:02 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +          resData.queries.nextPage === undefined
請看 while 的條件

2024-08-21 07:00 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
這是跑出來得結果，和你所認為的有差距
![Snipaste_2024-08-21_14-57-41](https://github.com/user-attachments/assets/715c97f8-31dd-4654-b8a1-2bb8a59368a1)
![Snipaste_2024-08-21_14-59-04](https://github.com/user-attachments/assets/b2a87deb-725a-4d07-9b9b-1277f5bef5f7)

2024-08-21 07:05 UTC, erase2004 reviewed
https://github.com/mirror-media/Adam/pull/1042#discussion_r1724508317
這部份依舊還有問題

2024-08-21 07:05 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +    let startIndex = params.startFrom || 1
`params.takeAmout` 和 `params.startIndex` 目前總是 `undefined`

2024-08-21 08:59 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +    let startIndex = params.startFrom || 1
感謝提醒，已於 [b60c983](https://github.com/mirror-media/Adam/pull/1042/commits/b60c983b7589689083c623f120914a28511c4d57) 修改，並確定能在 local 上正常運行。

2024-08-21 09:00 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
對齁..........在 [b60c983](https://github.com/mirror-media/Adam/pull/1042/commits/b60c983b7589689083c623f120914a28511c4d57) 嘗試加上一個變數 fetchAmount 確保不會遇到此種狀況。

2024-08-21 09:00 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +          resData.queries.nextPage === undefined
感謝提醒，已於 [b60c983](https://github.com/mirror-media/Adam/pull/1042/commits/b60c983b7589689083c623f120914a28511c4d57) 移除

2024-08-21 11:32 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +  startFrom: number().optional().integer().positive(),
含有 `max(100)` 的限制

2024-08-21 11:32 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
PROGRAMABLE_SEARCH_LIMIT_START 未被使用

2024-08-21 11:32 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +  startFrom: number().optional().integer().positive(),
含有 `min(1)` 的限制

2024-08-21 11:32 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
目前 `adjustedStart` 和 `fetchAmount` 的計算是有問題的，可以先用一個 function 來試著找出正確的結果
```TypeScript
function answer(start: number, take: number): [number, number] {
   // TODO; implement calculation logic
   
   return [adjustedStart, fetchAmount]
}
```
![Snipaste_2024-08-21_19-27-45](https://github.com/user-attachments/assets/c8c2bfdf-2813-4f42-aa63-fbe5cb5a6feb)
![Snipaste_2024-08-21_19-27-51](https://github.com/user-attachments/assets/c2c398ef-0246-4f02-b1ab-2a91ee529c4d)

2024-08-21 16:04 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +  startFrom: number().optional().integer().positive(),
感謝提醒，已於 [d8fcdc5](https://github.com/mirror-media/Adam/pull/1042/commits/d8fcdc5f2608df2afeed577b83683b9bf2e6e478) 補上

2024-08-21 16:04 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
感謝提醒，已於 [d8fcdc5](https://github.com/mirror-media/Adam/pull/1042/commits/d8fcdc5f2608df2afeed577b83683b9bf2e6e478) 移除

2024-08-21 16:04 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +  startFrom: number().optional().integer().positive(),
感謝提醒，已於 [d8fcdc5](https://github.com/mirror-media/Adam/pull/1042/commits/d8fcdc5f2608df2afeed577b83683b9bf2e6e478) 補上

2024-08-21 16:51 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
列了個表幫我自己釐清，修改過後幾個 edge case 長這樣：

| start | take | adjustedStart | endIndex | fetchAmount |
|-------|------|---------------|----------|-------------|
| 9     | 1    | 1             | 10       | 10          |
| 9     | 2    | 1             | 20       | 20          |
| 11    | 15   | 11            | 30       | 20          |
| 21    | 5    | 21            | 30       | 10          |
| 25    | 10   | 21            | 40       | 20          |
| 5     | 10   | 1             | 10       | 10          |
| 15    | 5    | 11            | 20       | 10          |
| 27    | 4    | 21            | 30       | 10          |
| 1     | 20   | 1             | 20       | 20          |
| 14    | 10   | 11            | 20       | 10          |
| 32    | 8    | 31            | 40       | 10          |
| 37    | 15   | 31            | 50       | 20          |
| 42    | 7    | 41            | 50       | 10          |
| 46    | 5    | 41            | 50       | 10          |
| 55    | 12   | 51            | 70       | 20          |
| 61    | 9    | 61            | 70       | 10          |
詳細修改可參見：[97174c0](https://github.com/mirror-media/Adam/pull/1042/commits/97174c052edc9bd463abcac45f37d7094719cd2c)

2024-08-22 03:42 UTC, erase2004 reviewed
## 程式是對了，但[這裡面](https://github.com/mirror-media/Adam/pull/1042#discussion_r1725416571)有兩個錯誤


![Snipaste_2024-08-22_11-26-52](https://github.com/user-attachments/assets/cd2d1e7b-f7ff-4f65-8d03-6fbd9da93a54)
![Snipaste_2024-08-22_11-27-45](https://github.com/user-attachments/assets/a35f1c66-da4a-4803-bc51-7640accf0120)

## `/pages/search` 舊版的行為也要處理一下
https://github.com/mirror-media/Adam/blob/dev/packages/mirror-media-search/hooks/useSearchArticles.js
舊版是 20 為一頁，和新版的 12 不同，需要設定 startFrom 和 takeAmount

2024-08-22 03:42 UTC, erase2004 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +      adjustedStart += 10
10 要用 `PROGRAMABLE_SEARCH_NUM` 表示

2024-08-22 03:42 UTC, erase2004 commented on packages/mirror-media-search/pages/search/[searchTerms].js
>          start: 1,
start 要換成 startFrom

2024-08-22 03:42 UTC, erase2004 commented on packages/mirror-media-search/components/searched-articles.js
> +          takeAmount: Math.min(
這裡 Math.min 似乎是多餘的，拿不滿 `PROGRAMABLE_SEARCH_PER_PAGE` 應該不會怎樣

2024-08-22 04:32 UTC, v61265 commented on packages/mirror-media-search/pages/search/[searchTerms].js
>          start: 1,
這個是不是舊版？v3 才是新版的樣子？需要一起改嗎？

2024-08-22 04:34 UTC, erase2004 commented on packages/mirror-media-search/pages/search/[searchTerms].js
>          start: 1,
還可以被存取到，有用到的可能，在 v2 完全汰換前，建議還是一併處理

2024-08-22 04:42 UTC, v61265 commented on packages/mirror-media-search/components/searched-articles.js
> +          takeAmount: Math.min(
看起來好像會出問題，以下是 google api 原始打法：
https://www.googleapis.com/customsearch/v1/siterestrict?cx=${參考我們目前的環境變數}&key=${機敏資料參考環境變數}&exactTerms=%E9%83%AD%E5%8F%B0%E9%8A%98&start=95&takeAmount=10
但不確定是不是我理解錯誤，所以先在 [37bbd48](https://github.com/mirror-media/Adam/pull/1042/commits/37bbd48f6156d35c7a1c175ba9da9ac4a7082be9) 拿掉 Math.min

2024-08-22 04:43 UTC, v61265 commented on packages/mirror-media-search/pages/search/[searchTerms].js
>          start: 1,
感謝提醒，已於 [37bbd48](https://github.com/mirror-media/Adam/pull/1042/commits/37bbd48f6156d35c7a1c175ba9da9ac4a7082be9) 修改
另外上方表格錯誤也已經訂正，十分感謝提醒～

2024-08-22 04:43 UTC, v61265 commented on packages/mirror-media-search/utils/api/programmable-search.js
> +      adjustedStart += 10
感謝提醒漏掉處！[37bbd48](https://github.com/mirror-media/Adam/pull/1042/commits/37bbd48f6156d35c7a1c175ba9da9ac4a7082be9)

2024-08-22 05:17 UTC, erase2004 commented on packages/mirror-media-search/components/searched-articles.js
> +          takeAmount: Math.min(
現在的 `getSearchResult` 應該不會出現抓超過 100 的上限，而出錯的情況，另外 querystring 中的 takeAmount 的參數實際上應為 num

2024-08-22 05:18 UTC, erase2004 approved these changes
LGTM 👏

2024-08-22 05:26 UTC, merged