feat(story): add gpt-ad PC_FLOATING
mirror-media/Adam pull request #437
Opened 2023-07-21 08:42 UTC by v61265

新增PC_汽車鐘錶文章頁：[mirror_pc_wat_200x200_floating] 廣告

2023-07-24 10:09 UTC, ChangRongXuan requested changes

2023-07-24 10:09 UTC, ChangRongXuan commented on packages/mirror-media-next/components/story/normal/index.js
> +const FloatingAdContainer = styled.div`
建議在手機版加上 `display: none` 移除元件，目前測試起來手機版還是會顯示 float 廣告。 
（如果是我測試錯誤再跟我說～）

```
 display: none

  ${({ theme }) => theme.breakpoint.xl} {
      display: block
      // ... 其餘 style 設定
  }
```

<img width="477" alt="截圖 2023-07-24 下午5 52 55" src="https://github.com/mirror-media/Adam/assets/104489150/c4e57c9c-e8b2-40eb-b8fa-8ce56e654a13">

2023-07-24 10:09 UTC, ChangRongXuan commented on packages/mirror-media-next/components/story/normal/index.js
>    }
nitpick：
好奇這段樣式為何要移除XD 目前 `StyledGPTAd_PC_E1` ＆ `StyledGPTAd_PC_E2` 設定上是設定成一致（同類型），如果要移除，建議 `StyledGPTAd_PC_E1` 也同步修改。

2023-07-24 10:09 UTC, ChangRongXuan commented on packages/mirror-media-next/components/story/normal/index.js
> +
nitpick: 如沒有特殊樣式要加，可直接使用 GPTAd 即可，不用特別建立 styled-component。

2023-07-24 10:09 UTC, ChangRongXuan commented on packages/mirror-media-next/components/story/normal/index.js
> +              <StyledGPTAd_PC_FLOATING
nitpick: 同上建議，`StyledGPTAd_PC_FLOATING`此處可直接使用 `<GPTAd>` 即可。

2023-07-25 17:44 UTC, v61265 commented on packages/mirror-media-next/components/story/normal/index.js
> +const FloatingAdContainer = styled.div`
感謝發現巨大 bug！已於 [acf0d23](https://github.com/mirror-media/Adam/pull/437/commits/acf0d234f439aeed01d700368b5e7e91460abc46) 修改。

2023-07-25 17:44 UTC, v61265 commented on packages/mirror-media-next/components/story/normal/index.js
>    }
這是不小心刪到的！超感謝提醒！已於 [acf0d23](https://github.com/mirror-media/Adam/pull/437/commits/acf0d234f439aeed01d700368b5e7e91460abc46) 加回去 ><

2023-07-25 17:44 UTC, v61265 commented on packages/mirror-media-next/components/story/normal/index.js
> +
感謝提醒，已於 [acf0d23](https://github.com/mirror-media/Adam/pull/437/commits/acf0d234f439aeed01d700368b5e7e91460abc46) 修改。

2023-07-26 07:36 UTC, ChangRongXuan approved these changes
拍謝晚回，剛剛看過修正部分，看起來沒什麼問題了
LGTM 🥇 🎉 👍

2023-07-26 11:00 UTC, merged