feat(papermag): get data from newebpay and render mock data
mirror-media/Adam pull request #537
Opened 2023-09-13 18:39 UTC by v61265

### Notable Chang
- 拿到藍新的資料解密
- 選擇 render 結果

2023-09-15 09:10 UTC, erase2004 requested changes

2023-09-15 09:10 UTC, erase2004 commented on packages/mirror-media-next/utils/papermag.js
> +function merchandiseWithShippingFee(merchandise) {
這個目前沒用到

2023-09-15 09:10 UTC, erase2004 commented on packages/mirror-media-next/components/papermag/subscribe-papermag-form.js
這樣處理其實有個問題，在選擇運費的情況下，要關聯的 merchandise 應為 `magazine_one_year_with_shipping_fee` 或 `magazine_two_year_with_shipping_fee`，但這裡統一使用 `magazine_one_year` 或 `magazine_two_year`，這樣到交易結果時，使用者永遠只會看到沒有運費的錯誤結論。

2023-09-15 09:10 UTC, erase2004 commented on packages/mirror-media-next/components/papermag/succeeded.js
> +    let numberStr = number.toString()
可以考慮用 `Number.prototype.toLocaleString()` 來做處理了，
例如：`Number(number).toLocaleString('en-US')`

2023-09-15 09:10 UTC, erase2004 commented on packages/mirror-media-next/components/papermag/succeeded.js
> +    let numberStr = number.toString()
funtion 命名也可以調整為 formatMoney 之類

2023-09-15 09:10 UTC, erase2004 commented on packages/mirror-media-next/utils/papermag.js
> +function merchandiseWithoutShippingFee(merchandiseCode) {
這 function 命名最大的問題是取得出來的內涵和 function 名稱不符，
我想調整為 `getMerchandiseAndShippingFeeInfo` 之類比較合理

2023-09-15 09:10 UTC, erase2004 commented on packages/mirror-media-next/utils/papermag.js
> +const PLAN_LIST = [
這個結構搭配 `merchandiseWithoutShippingFee` 的運作，其實頗混亂，單純化，我會把結構調整為
```
const PLAN_LIST = [
  {
     code: 'magazine_one_year',
     title: '一年鏡週刊 52 期',
     name: '一年鏡週刊 52 期',
     hasShippingFee: false,
     shippingFee: 0,
  },
  {
     code: 'magazine_one_year_with_shipping_fee',
     title: '一年鏡週刊 52 期加掛號運費',
     name: '一年鏡週刊 52 期',
     hasShippingFee: true,
     shippingFee: shippingFeePerYear,
  },
  ...
]
```
可以多寫一點，讓每一個成員獨立，這樣 `merchandiseWithoutShippingFee` 在處理時，調整為
`PLAN_LIST.find(plan => plan.code === merchandiseCode)`
就好了

2023-09-17 07:38 UTC, bibibobobi commented on packages/mirror-media-next/components/papermag/succeeded.js
> +    let numberStr = number.toString()
關於 format price 我有寫一個util `getNumberWithCommas` 可以直接引用

2023-09-18 05:58 UTC, bibibobobi commented on packages/mirror-media-next/pages/papermag/return.js
>            </button>
Toggle Failed 的 button，如果方便請幫我拿掉，感激～

2023-09-20 13:59 UTC, v61265 commented on packages/mirror-media-next/pages/papermag/return.js
>            </button>
好的，已於 [29a5737](https://github.com/mirror-media/Adam/pull/537/commits/29a57376ea95974f6c3264b69df774bb2ec64426) 修正！

2023-09-20 15:33 UTC, v61265 commented on packages/mirror-media-next/utils/papermag.js
> +const PLAN_LIST = [
感謝提醒，以上問題皆於 [4700dab](https://github.com/mirror-media/Adam/pull/537/commits/4700dab550ccf6aba61ba8082fc6a191e33131b0) refactor。

2023-09-20 15:33 UTC, v61265 commented on packages/mirror-media-next/utils/papermag.js
> +function merchandiseWithoutShippingFee(merchandiseCode) {
感謝提醒，已於 [4700dab](https://github.com/mirror-media/Adam/pull/537/commits/4700dab550ccf6aba61ba8082fc6a191e33131b0) 修正。

2023-09-20 15:33 UTC, v61265 commented on packages/mirror-media-next/components/papermag/succeeded.js
> +    let numberStr = number.toString()
感謝補充，已於 [4700dab](https://github.com/mirror-media/Adam/pull/537/commits/4700dab550ccf6aba61ba8082fc6a191e33131b0) 修正

2023-09-20 16:02 UTC, v61265 commented
### [56440ff](https://github.com/mirror-media/Adam/pull/537/commits/56440ff6a788677b67f2ce309d2f933a8bf385ca)
參考設計稿和 2.0 加上「折扣」欄位，並修改對應顏色。
設計稿：https://www.figma.com/file/qmocxMBHG6D7T2VPdydRWG/%E9%8F%A1%E9%80%B1%E5%88%8A---%E7%B6%B2%E7%AB%99?type=design&node-id=3169-15908&mode=design&t=06Y2zjgaAUJLrYFJ-0
預覽：
<img width="984" alt="截圖 2023-09-20 下午11 58 54" src="https://github.com/mirror-media/Adam/assets/66636137/b8092657-354c-4b76-af42-c1f5f3e59f36">

2023-09-21 02:31 UTC, bibibobobi reviewed
感謝新增折扣，但剛去看 3.0 [設計稿](https://www.figma.com/file/7HQsDCoUUElgLkVwJjVdg8/%E9%80%B1%E5%88%8A%E7%B6%B2%E7%AB%993.0?node-id=3868%3A16369&mode=dev) 顏色是0.87，不確定為何要改成 0.66？

2023-09-21 02:31 UTC, erase2004 commented on packages/mirror-media-next/components/papermag/succeeded.js
> +                <span>{itemName || '鏡週刊紙本雜誌 52 期'}</span>
在沒有資料的情況下，應該不做預設文字顯示，避免產生誤會？

2023-09-21 02:31 UTC, erase2004 commented on packages/mirror-media-next/components/papermag/succeeded.js
> +                  共<span className="number">{itemCount || 1}</span>份
在沒有資料的情況下，應該不做預設文字顯示，避免產生誤會？

2023-09-21 02:31 UTC, erase2004 commented on packages/mirror-media-next/pages/papermag/return.js
> +    const infoData = await parseBody(req, '1mb')
感覺需要註解，標示這裡為何需要用這個方法，
例如資料來源：https://github.com/vercel/next.js/discussions/14979

2023-09-21 02:31 UTC, erase2004 commented on packages/mirror-media-next/pages/papermag/return.js
> +    if (result.errors) console.log(result.errors[0].message)
GQL query 有 error，但程式繼續處理，並做顯示？

2023-09-21 02:31 UTC, erase2004 commented on packages/mirror-media-next/pages/papermag/return.js
> +    console.log(e)
應該使 `@twreporter/errors` 對 error 進行格式化包裝，並且使用 console.error 輸出

2023-09-21 09:17 UTC, v61265 commented on packages/mirror-media-next/pages/papermag/return.js
> +    if (result.errors) console.log(result.errors[0].message)
原來 gql 就會做處理了！那我先拿掉？

2023-09-21 09:19 UTC, v61265 commented on packages/mirror-media-next/pages/papermag/return.js
> +    console.log(e)
感謝提醒，已於 [66a1c82](https://github.com/mirror-media/Adam/pull/537/commits/66a1c82b629d549f49c53da22693b2bd1d9c571f) 新增。

2023-09-21 09:20 UTC, v61265 commented on packages/mirror-media-next/components/papermag/succeeded.js
> +                <span>{itemName || '鏡週刊紙本雜誌 52 期'}</span>
有道理，先於 [089ea4f](https://github.com/mirror-media/Adam/pull/537/commits/089ea4fe255c7f705c541b9ea4b611af30ab67c2) 移除。

2023-09-21 09:20 UTC, v61265 commented on packages/mirror-media-next/components/papermag/succeeded.js
> +                  共<span className="number">{itemCount || 1}</span>份
先於 [089ea4f](https://github.com/mirror-media/Adam/pull/537/commits/089ea4fe255c7f705c541b9ea4b611af30ab67c2) 移除。

2023-09-21 09:20 UTC, v61265 commented on packages/mirror-media-next/pages/papermag/return.js
> +    const infoData = await parseBody(req, '1mb')
感謝提醒，已於 [66a1c82](https://github.com/mirror-media/Adam/pull/537/commits/66a1c82b629d549f49c53da22693b2bd1d9c571f) 新增～

2023-09-21 09:29 UTC, v61265 commented
> 感謝新增折扣，但剛去看 3.0 [設計稿](https://www.figma.com/file/7HQsDCoUUElgLkVwJjVdg8/%E9%80%B1%E5%88%8A%E7%B6%B2%E7%AB%993.0?node-id=3868%3A16369&mode=dev) 顏色是0.87，不確定為何要改成 0.66？

不好意思是我看錯設計稿，目前已更正如下：
<img width="1440" alt="截圖 2023-09-21 下午5 28 40" src="https://github.com/mirror-media/Adam/assets/66636137/4002d4cc-29c2-4049-a408-580b8391403d">

2023-09-21 09:40 UTC, erase2004 reviewed
https://github.com/mirror-media/Adam/pull/537#discussion_r1326988547
這個問題發另一個 PR 處理？

2023-09-21 09:40 UTC, erase2004 commented on packages/mirror-media-next/pages/papermag/return.js
> +    if (result.errors) console.log(result.errors[0].message)
well，我的意思是指，「程式執行到這裡，抓到 graphql 回傳錯誤訊息，而在這裡的處理只有紀錄錯誤訊息，但程式沒有中斷執行」，這樣的行為是符合預期的？

2023-09-21 09:51 UTC, bibibobobi commented on packages/mirror-media-next/components/papermag/succeeded.js
> +              <DetailItem className="light-grey">運費</DetailItem>
`付款金額`跟`運費`改回`<Item>` 應該就不用另外加 `className="light-grey"` 了，不好意思當初命名有點 confusing 😅，但維持這樣不改應該也沒關係，我看這邊 UI 部分沒有問題了～

2023-09-21 10:03 UTC, bibibobobi commented on packages/mirror-media-next/components/papermag/succeeded.js
> +              <Price>NT$ {getNumberWithCommas(costWithoutShipping)}</Price>
發現這邊的 costWithoutShipping 似乎已經是折扣後的內容，但後面扣掉 discount 80之後，total 卻變回原價，似乎是相反了

2023-09-21 15:48 UTC, v61265 commented on packages/mirror-media-next/components/papermag/succeeded.js
> +              <Price>NT$ {getNumberWithCommas(costWithoutShipping)}</Price>
寫到昏頭了 XD 已於 [36931fd](https://github.com/mirror-media/Adam/pull/537/commits/36931fd212853fd3c8fa476fc1a692f964137120) 修正，感謝提醒！

2023-09-21 15:48 UTC, v61265 commented on packages/mirror-media-next/components/papermag/succeeded.js
> +              <DetailItem className="light-grey">運費</DetailItem>
已於 [f1a2895](https://github.com/mirror-media/Adam/pull/537/commits/f1a289518789bf19fff026959ec7bf313882331f) 修正，感謝提醒！

2023-09-21 15:53 UTC, v61265 commented
> well，我的意思是指，「程式執行到這裡，抓到 graphql 回傳錯誤訊息，而在這裡的處理只有紀錄錯誤訊息，但程式沒有中斷執行」，這樣的行為是符合預期的？

不好意思一開始沒有理解，這確實是一個問題，我在 [cdd428f](https://github.com/mirror-media/Adam/pull/537/commits/cdd428f39d74a5d918e5f460f3e4fd5fce0e437e) 將其統一丟到 catch 了，感謝提醒！

2023-09-21 15:57 UTC, v61265 commented on packages/mirror-media-next/components/papermag/subscribe-papermag-form.js
抱歉漏回這個，本來被註解的地方似乎被改掉了，有點忘記該問題本來是指什麼，也許明天當面討論後我再將結論統一整理於此，不好意思 ><

2023-09-22 03:01 UTC, v61265 commented on packages/mirror-media-next/components/papermag/subscribe-papermag-form.js
懂意思了，已於 https://github.com/mirror-media/Adam/pull/607 修改，再麻煩 code review 一下，感謝！

2023-09-22 04:46 UTC, erase2004 approved these changes
LGTM 👏

2023-09-22 05:14 UTC, bibibobobi approved these changes

2023-09-22 05:14 UTC, merged