feat(mm-next/papermag): fetch DB on return page
mirror-media/Adam pull request #918
Opened 2024-03-15 07:17 UTC by v61265

### 描述
- 紙本雜誌 render 付款結果頁（含Israfel & 藍新資訊）

### 討論
- 禮拜一實體可以討論哪些地方需要加上「錯誤處理：前台顯示錯誤頁 /order-fail」（return 頁面應該都不用？）

2024-03-18 06:07 UTC, erase2004 requested changes
1. 應該 import apollo client 進來作 graphql query
2. graphql 內容應該放在 `apollo/` 底下
3. API 改打 `/member/graphql`，另外，query 格式會有變動

請 @caesarWHLee 也確認目前週刊 3.0 是不是這樣進行管理

2024-03-19 05:21 UTC, v61265 commented
> 1. 應該 import apollo client 進來作 graphql query
> 2. graphql 內容應該放在 `apollo/` 底下
> 3. API 改打 `/member/graphql`，另外，query 格式會有變動
> 
> 請 @caesarWHLee 也確認目前週刊 3.0 是不是這樣進行管理

感謝說明，已於 [d261511](https://github.com/mirror-media/Adam/pull/918/commits/d261511f0a9eb8c9c135f4c6ed48ae295fec29d7) 修改一次，想再麻煩看看有沒有缺漏，感謝！

2024-03-19 06:29 UTC, erase2004 requested changes

2024-03-19 06:29 UTC, erase2004 commented on packages/mirror-media-next/apollo/query/magazine-orders.js
> +      itemCount
在設計稿當中，需要呈現的資訊有派送備註，但實際在購買時，沒有寫入該欄位的數值，需要請設計與 PM 確認該欄位是否還需要呈現，另外，2.0 有呈現訂購人地址資訊，所以會需要 purchaseAddress  資訊，3.0 按照設計來看是沒有，應該不用這個資訊?
![Snipaste_2024-03-19_14-23-49](https://github.com/mirror-media/Adam/assets/1367757/56a8924c-6f80-4977-8a41-3c00cf12f092)

2024-03-19 06:29 UTC, erase2004 commented on packages/mirror-media-next/pages/papermag/return.js
> +  ISRAFEL_ORIGIN,
未被使用，應移除

2024-03-19 07:23 UTC, caesarWHLee commented
> 應該 import apollo client 進來作 graphql query
graphql 內容應該放在 apollo/ 底下
API 改打 /member/graphql，另外，query 格式會有變動
請 @caesarWHLee 也確認目前週刊 3.0 是不是這樣進行管理

是這樣管理沒錯，感謝

2024-03-19 16:07 UTC, v61265 commented on packages/mirror-media-next/apollo/query/magazine-orders.js
> +      itemCount
感謝提醒，已於 [2787ec6](https://github.com/mirror-media/Adam/pull/918/commits/2787ec6f4f3c6b3489a40420979d1f02f63fce55) 修改

2024-03-19 16:07 UTC, v61265 commented on packages/mirror-media-next/pages/papermag/return.js
> +  ISRAFEL_ORIGIN,
感謝提醒，已於 [2787ec6](https://github.com/mirror-media/Adam/pull/918/commits/2787ec6f4f3c6b3489a40420979d1f02f63fce55) 修改

2024-03-20 03:27 UTC, erase2004 approved these changes

2024-03-20 03:27 UTC, erase2004 commented on packages/mirror-media-next/pages/papermag/return.js
> +    const decryptInfoData = result?.data?.magazineOrders?.[0]
比起命名為 `decryptInfoData`，命名為 `magazineOrderData` 會比較貼切，畢竟他的資料內容不是經過解密的。

2024-03-20 08:03 UTC, v61265 commented on packages/mirror-media-next/pages/papermag/return.js
> +    const decryptInfoData = result?.data?.magazineOrders?.[0]
感謝提醒，已於 [94c8157](https://github.com/mirror-media/Adam/pull/918/commits/94c81573015b66873e7dc1b9d7be226750d2e176) 修改

2024-03-20 08:03 UTC, merged