feat(mm-next): add profile page
mirror-media/Adam pull request #974
Opened 2024-05-06 03:38 UTC by nihclil

**Changes**
* profile page UI

**尚未完成**
* 點擊頁面其他區塊，收合已開啟選單
* 點擊其他選單，收合已開啟選單

2024-05-06 13:46 UTC, erase2004 requested changes
初步 review，觀察到以下問題

1. 在特定顯示寬度下，表單的左側和右側會超出 header 的左側與右側
![Snipaste_2024-05-06_21-09-53](https://github.com/mirror-media/Adam/assets/1367757/f58226e4-4fa9-462a-880a-d01d5a951744)

2. 寬度設定應該設定在 index.js#Page 上，而不是 UserProfileForm 和 UserDeletionForm，用 parent 來限制 child
![Snipaste_2024-05-06_21-11-51](https://github.com/mirror-media/Adam/assets/1367757/8633610b-8310-4dd7-a011-bf77dc470a76)
![Snipaste_2024-05-06_21-12-11](https://github.com/mirror-media/Adam/assets/1367757/19ac7902-5a0c-4f1a-8886-214c45aebe9a)

3. FormWrapper 可以改用 flexbox，並且搭配 row-gap，讓底下的群組等高度間隔
![Snipaste_2024-05-06_21-21-20](https://github.com/mirror-media/Adam/assets/1367757/0745423f-9657-4233-94a6-dc9027824906)

4. Dropdown 開啟後，右側的 icon 沒有朝上
![Snipaste_2024-05-06_21-38-49](https://github.com/mirror-media/Adam/assets/1367757/92457ce1-8085-4dd6-a288-32fa3613e812)

2024-05-06 13:46 UTC, erase2004 commented on packages/mirror-media-next/apollo/query/profile.js
> + * @property {string} firebaseId
`firebaseId` 到 `address`，這些 field 的 type 可能是 `null`

2024-05-06 13:46 UTC, erase2004 commented on packages/mirror-media-next/pages/profile/index.js
> +import Layout from '../../components/shared/layout'
應該改用 `LayoutFull`

2024-05-06 13:46 UTC, erase2004 commented on packages/mirror-media-next/pages/profile/index.js
> + * @param {Object[]} props.sectionsData
sectionsData, topicsData 沒有用到，先移除

2024-05-06 13:46 UTC, erase2004 commented on packages/mirror-media-next/pages/profile/index.js
> + * @return {JSX.Element}
用 `@returns`

2024-05-06 13:46 UTC, erase2004 commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> +const SelectBox = styled.div`
有 custom prop，請增加 JSDoc comment
ref: https://github.com/mirror-media/Adam/blob/b4aa0947235930b9875a859827c7f51ae6b12090/packages/mirror-media-next/components/shared/hint.js#L31

2024-05-06 13:46 UTC, erase2004 commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> +      {isOpen && (
考慮改用 `display: none` 的方式來隱藏選項，而不是該區塊選項直接消失

2024-05-07 12:09 UTC, nihclil commented on packages/mirror-media-next/apollo/query/profile.js
> + * @property {string} firebaseId
感謝，於 [9259754]([9259754](https://github.com/mirror-media/Adam/pull/974/commits/9259754e5275461a8d9af0a8708679715258978d) ) 修正。

2024-05-07 12:12 UTC, nihclil commented on packages/mirror-media-next/pages/profile/index.js
> +import Layout from '../../components/shared/layout'
謝謝，修正於 [48f022a](https://github.com/mirror-media/Adam/pull/974/commits/48f022a6132c51a4658960495f7dd1a0f0c9c494)。

2024-05-07 12:12 UTC, nihclil commented on packages/mirror-media-next/pages/profile/index.js
> + * @param {Object[]} props.sectionsData
謝謝，修正於 [11e7161](https://github.com/mirror-media/Adam/pull/974/commits/11e716152f3c086f3ab8fe8230c2c47aae27cb30)

2024-05-07 12:13 UTC, nihclil commented on packages/mirror-media-next/pages/profile/index.js
> + * @return {JSX.Element}
謝謝，修正於 [ede23e0](https://github.com/mirror-media/Adam/pull/974/commits/ede23e0a17a0db5e788a3682fa8b24d629529f20)

2024-05-07 12:14 UTC, nihclil commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> +const SelectBox = styled.div`
謝謝，修正於 [b9531cd](https://github.com/mirror-media/Adam/pull/974/commits/b9531cd71d0e4207c76862d2eadfceb966357d55)

2024-05-07 12:15 UTC, nihclil commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> +      {isOpen && (
謝謝，修正於 [17376fe](https://github.com/mirror-media/Adam/pull/974/commits/17376fecd5ed8ad60bfbb5d3adeabe79040258ee)

2024-05-08 10:20 UTC, erase2004 reviewed
Dropdown Menu 會需要針對 click outside 的情況來自動關閉

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/pages/profile/index.js
> +  margin: auto;
`auto` 應該侷限於左右

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/pages/profile/index.js
> +  margin: auto;
應該有 `max-width: 596px`，避免 md 以下時，表單的左右邊界超出 header 的左右側

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/pages/profile/index.js
> +    width: 596px;
這裡數值應該是 `600px`，搭配 `max-width: unset`

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-deletion-form.js
> +  justify-content: center;
多餘的?

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-deletion-form.js
> +  a {
`a` 的 style 建議改用
```JavaScript
const someVariable = styled(Link)``
```
的方式去處理

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-deletion-form.js
> +  color: #00000080;
hex code 僅建議使用 6 碼，在有表示 alpha 值的情況下，使用 rgba 的形式比較好

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-deletion-form.js
「刪除會員連結」與「儲存按鈕」的間距與設計稿不符

![Snipaste_2024-05-08_16-43-29](https://github.com/mirror-media/Adam/assets/1367757/d59310b1-aacd-47d6-89ca-c7a73872c4ae)
![Snipaste_2024-05-08_16-44-25](https://github.com/mirror-media/Adam/assets/1367757/544579c8-b289-4313-b0fc-e963b5164ff4)
![Snipaste_2024-05-08_16-44-53](https://github.com/mirror-media/Adam/assets/1367757/2bea9c8a-5d7e-480e-b8b4-3955b368ef7c)

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +    <FormWrapper>
`FormWrapper` 看起來沒特別作用，應該不用多這一層，可以考慮以下方法：
1. 用 Fragment (https://react.dev/reference/react/Fragment)
2. 把 `Title` 放到 `profile/index.js` 底下，這個元件由 `Form` 當 root

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +  gap: 40px;
限縮在 `row-gap`

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-profile-form.js
規格需要被釐清和確認，為什麼生日和西元年的間距，從 320 -> 768 時會產生變化，但是地址與國家的間距卻沒有，需要確認這兩者的行為是否可以一致，要就都有變化，或者都沒有變化。

![Snipaste_2024-05-08_17-08-19](https://github.com/mirror-media/Adam/assets/1367757/563c5c55-b6d5-4b6d-9727-2453e64529a1)
![Snipaste_2024-05-08_17-08-36](https://github.com/mirror-media/Adam/assets/1367757/2d443a5d-47fb-47e5-9ade-2244667e9b38)
![Snipaste_2024-05-08_17-08-51](https://github.com/mirror-media/Adam/assets/1367757/2dff125d-1bae-4a05-a492-d8b6a43ef161)
![Snipaste_2024-05-08_17-09-02](https://github.com/mirror-media/Adam/assets/1367757/da8aeda9-cc67-48d3-afd5-3bd33da80b15)

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-profile-form.js
需要確認，320 的情況下，變更密碼的按鈕是否要顯示？
![Snipaste_2024-05-08_17-15-03](https://github.com/mirror-media/Adam/assets/1367757/9417ecea-364c-410c-8c6a-ae2f66f5fd0a)
![Snipaste_2024-05-08_17-15-10](https://github.com/mirror-media/Adam/assets/1367757/8e45002d-960e-4d20-ad77-e83018a85b8a)

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> +  border: 1px solid ${(props) => (props.isOpen ? '#000000de' : '#0000004d')};
在使用 props 的地方，需要加上 `/** @param {some_type} variable_name_of_props */` 的 JSDoc，
參考 https://github.com/mirror-media/Adam/blob/b4aa0947235930b9875a859827c7f51ae6b12090/packages/mirror-media-next/components/shared/hint.js#L41

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> +  z-index: 100;
重複使用

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> +    transform: ${(props) =>
可以改用
```CSS
transform-origin: 25% 75%;
transform: translateY(-50%)
  ${(props) => (props.isOpen ? 'rotate(135deg);' : 'rotate(-45deg)')};
```
的方式來處理

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> + * @param {object} props.options
針對 options 應該定義一個 type 來做使用，並且讓使用端 ([/profile/user-profile-form.js](https://github.com/mirror-media/Adam/pull/974/files#diff-5cf9b7fcb44a5b74ef651f87514b1c73e46abf3c36531acb51d6d6c64e3e636a)) 也可以 import 這個 type

2024-05-08 10:20 UTC, erase2004 commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> + * @param {function(string):void} props.onSelect
應該用 `(value: string) => void` 的形式

2024-05-09 12:23 UTC, nihclil commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> + * @param {function(string):void} props.onSelect
為什麼原本那樣寫不好？🧐

2024-05-09 14:16 UTC, erase2004 commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> + * @param {function(string):void} props.onSelect
JSDoc 作為過渡期使用，寫法上能越貼近 TypeScript 的話，未來搬移成本上較低，不過目前還不習慣 `inline signature` 形式的話，維持原本的型式也是可以

2024-05-09 15:02 UTC, nihclil commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> +  border: 1px solid ${(props) => (props.isOpen ? '#000000de' : '#0000004d')};
每一行用到 props 的前面都要加嗎

2024-05-10 02:34 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-deletion-form.js
> +  a {
因為看起來比較清楚嗎 🧐

2024-05-10 03:09 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-deletion-form.js
> +  a {
恩

2024-05-10 15:45 UTC, nihclil commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> +  z-index: 100;
感謝，修改於 [9be3f8b](https://github.com/mirror-media/Adam/pull/974/commits/9be3f8bcd1fc3b03d214c8f71838ac6ef57943bc)

2024-05-10 15:46 UTC, nihclil commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> +    transform: ${(props) =>
感謝，修改於 [b2a72ab](https://github.com/mirror-media/Adam/pull/974/commits/b2a72ab4ea60896668864b442011f0f46653cf11)

2024-05-10 15:48 UTC, nihclil commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> + * @param {object} props.options
感謝，修改於 [b2df98b](https://github.com/mirror-media/Adam/pull/974/commits/b2df98bc2715252d3e74682b82dc1b0d0e443681)

2024-05-10 15:50 UTC, nihclil commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> + * @param {function(string):void} props.onSelect
感謝，修改於 [f93c80b](https://github.com/mirror-media/Adam/pull/974/commits/f93c80be97d0d0e726d05873ffb6c32f0e2509ba)

2024-05-10 15:50 UTC, nihclil commented on packages/mirror-media-next/components/profile/dropdown-menu.js
> +  border: 1px solid ${(props) => (props.isOpen ? '#000000de' : '#0000004d')};
修改於 [78e8e04](https://github.com/mirror-media/Adam/pull/974/commits/78e8e0431201cf498850dffcda88dd4f786deb1a)

2024-05-10 15:51 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +    <FormWrapper>
感謝，修改於 [9818594](https://github.com/mirror-media/Adam/pull/974/commits/9818594b95154021322817e6ac3ae4b563f29339)

2024-05-10 15:51 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +  gap: 40px;
感謝，修改於 [a150789](https://github.com/mirror-media/Adam/pull/974/commits/a150789cfef2d32ae127df68d0e4e1965b53668b)

2024-05-10 15:53 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-deletion-form.js
> +  color: #00000080;
感謝，修改於 [0c43567](https://github.com/mirror-media/Adam/pull/974/commits/0c43567770c4356300bf7c3cbdd502832fb81cb5) [8725782](https://github.com/mirror-media/Adam/pull/974/commits/8725782cde87047bba2a0562da2b5ab1d46b7b84)

2024-05-10 15:54 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-deletion-form.js
> +  a {
感謝，修改於 [71df23e](https://github.com/mirror-media/Adam/pull/974/commits/71df23e5827c1f43da31c2d614ef916d3eacc263)

2024-05-10 15:54 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-deletion-form.js
> +  justify-content: center;
感謝，修改於 [797c5ad](https://github.com/mirror-media/Adam/pull/974/commits/797c5ad6e854dbf83791577c5cd9b03aeca8601d)

2024-05-10 15:56 UTC, nihclil commented on packages/mirror-media-next/pages/profile/index.js
> +  margin: auto;
感謝，修改於 [077c627](https://github.com/mirror-media/Adam/pull/974/commits/077c6278bb15cec8fb2fff7628fe30babe6c0678) [63bc3be](https://github.com/mirror-media/Adam/pull/974/commits/63bc3be81131a2c8e1a92a14f9bd95ffe4a20114)

2024-05-10 15:56 UTC, nihclil commented on packages/mirror-media-next/pages/profile/index.js
> +    width: 596px;
感謝，修改於 [1a65fc1](https://github.com/mirror-media/Adam/pull/974/commits/1a65fc17e59a428b04bb6fbbb83a63c81d48af98)

2024-05-10 16:00 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-profile-form.js
已確認過規格，320 時間距為 8px，謝謝提醒！修改於 [1b354ad](https://github.com/mirror-media/Adam/pull/974/commits/1b354ad3b0c93c92555ed8b05151e57acd30ab76)。

2024-05-10 16:01 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-profile-form.js
已確認過規格，變更密碼的按鈕應該顯示，謝謝提醒！修改於 [3a5bf6b](https://github.com/mirror-media/Adam/pull/974/commits/3a5bf6bfef797c15f574e0a81e6b96896564696a)。

2024-05-10 16:04 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-deletion-form.js
感謝提醒，修改於 [713f659](https://github.com/mirror-media/Adam/pull/974/commits/713f659b6c9c0caa8952b25f8a82b86e8facf991)

2024-05-10 16:06 UTC, nihclil commented
> Dropdown Menu 會需要針對 click outside 的情況來自動關閉

感謝，修改於 [57b48f6](https://github.com/mirror-media/Adam/pull/974/commits/57b48f6867079619461e1a40997585123cf86ded)

2024-05-12 15:58 UTC, erase2004 commented on packages/mirror-media-next/pages/profile/index.js
> +  max-width: 596px;
`max-width` 調整為 `min(596px, 100vw)`，並且搭配 `overflow-x: hidden`， 避免 email 資訊過長時，產生橫向捲動

2024-05-12 15:58 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +        <EmailWrapper>
email 過長的情況下，超出的部份應該要換行？
![Snipaste_2024-05-12_23-22-53](https://github.com/mirror-media/Adam/assets/1367757/f24a9501-27f8-44bb-914b-bc162afbca7b)

2024-05-12 15:58 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +            <DefaultButton>變更密碼</DefaultButton>
點擊後跳轉到 `/updatePassword`

2024-05-12 15:58 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-profile-form.js
姓名、性別和生日區塊的間距應該相同
![Snipaste_2024-05-12_23-38-44](https://github.com/mirror-media/Adam/assets/1367757/3286a058-a2e7-4cad-a398-4fc1a5a8350e)

2024-05-12 15:58 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +              <input id="year" placeholder="西元年" />
可以考慮用 `GenericTextInput` 元件來取代 `input`

2024-05-12 15:58 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +                onSelect={setSelectedMonth}
月份的 `placeholder` 資訊是 `月份`

2024-05-12 15:58 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +          <input id="phone" placeholder="電話" />
`placeholder` 資訊是 `請輸入電話`

2024-05-12 15:58 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +              <input id="address" placeholder="詳細地址" />
`placeholder` 資訊是 `請輸入街道、門號、巷弄、樓層等資訊`

2024-05-13 05:00 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +              <input id="address" placeholder="詳細地址" />
感謝，修改於 [d84eb81](https://github.com/mirror-media/Adam/pull/974/commits/d84eb8185975830732343b2d42fc6444cb0ef0bf)

2024-05-13 05:00 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +          <input id="phone" placeholder="電話" />
感謝，統一修改於 [d84eb81](https://github.com/mirror-media/Adam/pull/974/commits/d84eb8185975830732343b2d42fc6444cb0ef0bf)

2024-05-13 05:00 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +                onSelect={setSelectedMonth}
感謝，統一修改於 [d84eb81](https://github.com/mirror-media/Adam/pull/974/commits/d84eb8185975830732343b2d42fc6444cb0ef0bf)

2024-05-13 05:01 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-profile-form.js
感謝，修改於 [7c8a663](https://github.com/mirror-media/Adam/pull/974/commits/7c8a663dc686c2a1aaf8c2d5efe19a43a835f8a8)

2024-05-13 05:01 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +            <DefaultButton>變更密碼</DefaultButton>
感謝，修改於[537c345](https://github.com/mirror-media/Adam/pull/974/commits/537c345c4e5351eaea035831a142b20d35cdc6b0)

2024-05-13 05:02 UTC, nihclil commented on packages/mirror-media-next/pages/profile/index.js
> +  max-width: 596px;
感謝，修改於[b9ba3e8](https://github.com/mirror-media/Adam/pull/974/commits/b9ba3e82101b0e1e68496e03975b80b747592bd1)

2024-05-13 05:02 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +        <EmailWrapper>
感謝，修改於[b9ba3e8](https://github.com/mirror-media/Adam/pull/974/commits/b9ba3e82101b0e1e68496e03975b80b747592bd1)

2024-05-13 05:03 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +              <input id="year" placeholder="西元年" />
這個可能等之後再發 PR 修改，因為時間關係，要先往顯示資料的 task 前進

2024-05-13 13:17 UTC, erase2004 reviewed
這三個輸入框應該要等寬
![Snipaste_2024-05-13_21-14-31](https://github.com/mirror-media/Adam/assets/1367757/ee725fde-d249-4a45-a1f9-51ab7501e347)

2024-05-13 13:17 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +          <Link href="/updatePassword">
`DefaultButton` 上有 `onClick` 的 prop，應該用這個 prop 去做跳轉

2024-05-13 15:00 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +          <Link href="/updatePassword">
感謝，修改於 [336dcff](https://github.com/mirror-media/Adam/pull/974/commits/336dcffeaf4da30c2bdd58141be7b303626a9065)

2024-05-13 15:01 UTC, nihclil commented
> 這三個輸入框應該要等寬 ![Snipaste_2024-05-13_21-14-31](https://private-user-images.githubusercontent.com/1367757/330070445-ee725fde-d249-4a45-a1f9-51ab7501e347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTI3MTYsIm5iZiI6MTcxNTYxMjQxNiwicGF0aCI6Ii8xMzY3NzU3LzMzMDA3MDQ0NS1lZTcyNWZkZS1kMjQ5LTRhNDUtYTFmOS01MWFiNzUwMWUzNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMTUwMDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTJmZDk5M2JmZjNmN2RjNjIxYjFmZGU5MzU4ZDYxZmU3ODc3Yjg0M2FjM2MxODIwNWRiM2JmNTFlMjNmZGNiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8mIy938bEPtE8Dv-tRP0ZQVYRHcYNeGfnrYTua47OGs)

謝謝，修改於 [ce7c988](https://github.com/mirror-media/Adam/pull/974/commits/ce7c988dd878f3cc6f27f0b67bc9631b5f6fd611)

2024-05-14 02:37 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +  flex: 1;
建議用完整表示 `flex: 1 1 0` 的形式，這樣比較明確

2024-05-14 02:37 UTC, erase2004 commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +  useEffect(() => {
cityName 不需要成為 state，因為它是 `taiwanDisTrictOptions` 直接對應算出來的，
只需要 `const cityNames = taiwanDisTrictOptions.map ...` 即可，
又或者資料上過大，可以考慮用上 useMemo 來減少運算
ref: https://react.dev/reference/react/useMemo

2024-05-14 02:49 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +  useEffect(() => {
謝謝，修改於 [2417783](https://github.com/mirror-media/Adam/pull/974/commits/2417783d0b7cd6f521c238bd0cecd0e1f12bf3cf)

2024-05-14 02:49 UTC, nihclil commented on packages/mirror-media-next/components/profile/user-profile-form.js
> +  flex: 1;
謝謝，修改於[d69da33](https://github.com/mirror-media/Adam/pull/974/commits/d69da3334fbfba9b4073c79a260219deee436601)

2024-05-14 02:58 UTC, erase2004 approved these changes
Accepted 👏

2024-05-14 03:00 UTC, nihclil commented
麻煩你了，謝啦

2024-05-14 03:00 UTC, merged